=== jetzz-uwux/40260/xml/xml-00.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT direccion (nombrecompleto, correo, telefono, cumpleanios)>
<!ELEMENT nombrecompleto (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumpleanios (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== jetzz-uwux/40260/xml/xml-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE direccion SYSTEM "xml-00.dtd">
<direccion>
    <nombrecompleto>
    <nombre>Jetzaly Josmery</nombre>
    <apellido>T C</apellido>
    </nombrecompleto>
    <correo>12345@correo.com</correo>
    <telefono>12345567</telefono>
    <cumpleanios>
        <dia>22</dia>
        <mes>04</mes>
        <anio>2006</anio>
    </cumpleanios>
</direccion>
